'use client';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Building2, RefreshCw } from 'lucide-react';
import { formatEuro, formatNumber, formatPercent, formatDate } from '@/lib/dashboard-service';
import type { EnseigneStat, CustomerFollowup } from '@/lib/dashboard-types';
export function CaCentraleList({ enseignes }: { enseignes: EnseigneStat[] }) {
  const c = enseignes.filter(e => e.type === 'Centrale'); const t = c.reduce((s, e) => s + e.caHT, 0); if (!c.length) return null;
  return (<Card className="border-primary/40 dark:border-primary/40"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Building2 className="h-5 w-5 text-primary" /> Liste du CA Centrale</CardTitle><CardDescription>{c.length} enseigne(s) • CA HT : {formatEuro(t)}</CardDescription></CardHeader><CardContent><div className="max-h-80 overflow-y-auto rounded-md border border-primary/20 dark:border-primary/20"><Table><TableHeader className="sticky top-0 bg-primary/5 dark:bg-primary/10 z-10"><TableRow><TableHead className="w-10 text-center">#</TableHead><TableHead>Enseigne</TableHead><TableHead className="hidden md:table-cell">Agent</TableHead><TableHead className="text-right">BL</TableHead><TableHead className="text-right">CA HT</TableHead><TableHead className="text-right">Part</TableHead><TableHead className="text-right hidden sm:table-cell">Dern. cmd</TableHead></TableRow></TableHeader><TableBody>{c.map((e, i) => (<TableRow key={e.enseigne}><TableCell className="text-center text-sm text-slate-500">{i + 1}</TableCell><TableCell className="font-medium">{e.enseigne}</TableCell><TableCell className="hidden md:table-cell text-slate-600">{e.agent}</TableCell><TableCell className="text-right">{formatNumber(e.nbBl)}</TableCell><TableCell className="text-right font-semibold text-primary">{formatEuro(e.caHT)}</TableCell><TableCell className="text-right"><Badge variant="secondary" className="font-mono">{formatPercent(e.share / 100)}</Badge></TableCell><TableCell className="text-right hidden sm:table-cell text-slate-600">{formatDate(e.lastOrder)}</TableCell></TableRow>))}</TableBody></Table></div></CardContent></Card>);
}
export function RecurringClientsCard({ customers }: { customers: CustomerFollowup[] }) {
  const r = customers.filter(c => c.status === 'OK' && c.recurrence >= 0.3).sort((a, b) => b.caTotal - a.caTotal); if (!r.length) return null;
  return (<Card className="border-primary/40 dark:border-primary/40"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><RefreshCw className="h-5 w-5 text-primary" /> Clients récurrents</CardTitle><CardDescription>{r.length} client(s) récurrent(s)</CardDescription></CardHeader><CardContent><div className="max-h-80 overflow-y-auto rounded-md border border-primary/20 dark:border-primary/20"><Table><TableHeader className="sticky top-0 bg-primary/5 dark:bg-primary/10 z-10"><TableRow><TableHead>Enseigne</TableHead><TableHead className="hidden md:table-cell">Type</TableHead><TableHead className="text-right">BL Tot</TableHead><TableHead className="text-right">CA Total</TableHead><TableHead className="text-right hidden sm:table-cell">Dern. cmd</TableHead><TableHead className="text-right">Récurrence</TableHead></TableRow></TableHeader><TableBody>{r.map(c => (<TableRow key={c.enseigne}><TableCell className="font-medium">{c.enseigne}</TableCell><TableCell className="hidden md:table-cell"><Badge variant="outline">{c.type}</Badge></TableCell><TableCell className="text-right">{formatNumber(c.nbBlTotal)}</TableCell><TableCell className="text-right font-semibold text-primary">{formatEuro(c.caTotal)}</TableCell><TableCell className="text-right hidden sm:table-cell text-slate-600">{formatDate(c.lastOrder)}</TableCell><TableCell className="text-right"><Badge variant="secondary" className="font-mono bg-primary/15 text-primary">{formatPercent(c.recurrence)}</Badge></TableCell></TableRow>))}</TableBody></Table></div></CardContent></Card>);
}
